options:
  credentials:
    description: |
      The base64-encoded contents of a JSON file containing OpenStack credentials.

      The credentials must contain the following keys: auth-url, username, password,
      project-name, user-domain-name, and project-domain-name.

      It could also contain a base64-encoded CA certificate in endpoint-tls-ca key value.

      This can be used from bundles with 'include-base64://' (see
      https://jujucharms.com/docs/stable/charms-bundles#setting-charm-configurations-options-in-a-bundle),
      or from the command-line with 'juju config openstack credentials="$(base64 /path/to/file)"'.

      It is strongly recommended that you use 'juju trust' instead, if available.
    type: string
    default: ""
  auth-url:
    description: |
      The URL of the keystone API used to authenticate. On OpenStack control panels,
      this can be found at Access and Security > API Access > Credentials.
    type: string
    default: ""
  username:
    description: Username of a valid user set in keystone.
    type: string
    default: ""
  password:
    description: Password of a valid user set in keystone.
    type: string
    default: ""
  project-name:
    description: Name of project where you want to create your resources.
    type: string
    default: ""
  user-domain-name:
    description: Name of the user domain where you want to create your resources.
    type: string
    default: ""
  project-domain-name:
    description: Name of the project domain where you want to create your resources.
    type: string
    default: ""
  region:
    description: Name of the region where you want to create your resources.
    type: string
    default: ""
  endpoint-tls-ca:
    description: |
      A CA certificate that can be used to verify the target cloud API endpoints.
      Use 'include-base64://' in a bundle to include a certificate. Otherwise,
      pass a base64-encoded certificate (base64 of "-----BEGIN" to "-----END")
      as a config option in a Juju CLI invocation.
    type: string
    default: ""
  subnet-id:
    description: |
      Subnet ID from OpenStack that will be used to setup Load Balancers. Flag
      LoadBalancer becomes active on cloud.conf file only if this config is set.
    type: string
    default: ""
  floating-network-id:
    description: |
      Floating IP network ID that should be used to set FIPs for load balancers.
    type: string
    default: ""
  lb-method:
    description: |
      Specifies an algorithm load balancer, that should be one between ROUND_ROBIN,
      LEAST_CONNECTIONS, SOURCE_IP.
    type: string
    default: ""
  manage-security-groups:
    description: |
      Whether or not the Load Balancer should automatically manage security groups rule.
      In case it is set to false, Load Balancer rules will be added to project (tenant)
      default security-group. In case it is set to true, a new security-group will be
      created for each Load Balancer, as well as its corresponding rules.
      It is advised to set appropriate number of security-groups and rules.
    type: boolean
    default: false
  bs-version:
    description: |
      Used to override automatic version detection for block storage usage.
      Valid values are v1, v2, v3 and auto. When auto is specified automatic
      detection will select the highest supported version exposed by the
      underlying OpenStack cloud. If not set, will use the upstream default.
    type: string
    default: null
  trust-device-path:
    description: |
      In most scenarios the block device names provided by Cinder (e.g.
      /dev/vda) can not be trusted. This boolean toggles this behavior. Setting
      it to true results in trusting the block device names provided by Cinder.
      The value of false results in the discovery of the device path
      based on its serial number and /dev/disk/by-id mapping and is the
      recommended approach.  If not set, will use the upstream default.
    type: boolean
    default: null
  ignore-volume-az:
    description: |
      Used to influence availability zone use when attaching Cinder volumes.
      When Nova and Cinder have different availability zones, this should be
      set to true. This is most commonly the case where there are many Nova
      availability zones but only one Cinder availability zone. If not set,
      will use the upstream default.
    type: boolean
    default: null
