name: Python package

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Run Tox
        run: tox

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install charm-tools snap
        run: sudo snap install charm --classic

      - name: Build charm
        run: charm build

      - name: Publish charm
        env: # Or as an environment variable
          CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
        run: |
          echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies
          charm push /tmp/charm/builds/openstack-integrator
